'use strict';
let lang='en', data=null, realTask='macro', metric='sr', filter='All', predKey=null, predDomain='real', offset=16, modalTask=1;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const t=(en,zh)=>lang==='en'?en:zh;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categoryNames={Reasoning:['Reasoning','推理'],Manipulation:['Manipulation','物体操作'],Assembly:['Assembly','装配'],Generalization:['Generalization','泛化'],Precision:['Precision','精密操作'],'Long-Horizon':['Long-Horizon','长时序'],Memory:['Memory','记忆'],Open:['Open','开放任务']};
const category=c=>t(...(categoryNames[c]||[c,c]));
const englishMarkup=new Map($$('[data-en][data-zh]').map(el=>[el,el.innerHTML]));
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const abstractEn='Recent world action models draw on video generation priors to jointly predict future observations and robot actions. Adapting these priors to control requires determining how future predictions should guide policy learning. RAP-WAM combines predictive Rehearsal and Action Perturbations (RAP) with future-supervised queries and Coupled Action Projection for policy learning. Predictive rehearsal trains on model-generated inputs while retaining recorded targets, and accumulates recurring errors into a spatial prior. We perturb actions and measure changes in video predictions. Action-response-based spatiotemporal credit assignment combines these responses, prediction error, and the rehearsal prior to allocate visual supervision; spatially aggregating the responses determines supervision intensity across future action steps. No separate scoring network or deployment-time probe is required. The base learns from a video-pretrained backbone without intermediate pretraining on external embodied data. We evaluate the fixed base and its agent-refined, task-conditioned system. On 42 RoboDojo tasks, their average success rates are 12.85% and 15.62%, with Scores of 17.86 and 20.59. Across 15 real-robot tasks, the complete system achieves 89.00% task-macro-average success, exceeding the strongest of five baselines by 37.67 percentage points. Across 315 fixed-output simulation windows, 45.21% of response-top20 positions fall outside error-top20, revealing information beyond prediction error.';
const abstractZh='近期世界动作模型利用视频生成先验联合预测未来观测与机器人动作。将这些先验适配到控制，需要明确未来预测应如何指导策略学习。RAP-WAM将预测演练与动作扰动（predictive Rehearsal and Action Perturbations, RAP）同未来监督查询、耦合动作投影相结合，用于策略学习。预测演练以模型生成的输入训练，同时保留记录的监督目标，并将反复出现的误差累积为空间先验。我们扰动动作并测量视频预测的变化。动作响应驱动的时空信用分配结合这些响应、预测误差与演练先验来分配视觉监督；对响应进行空间汇总，确定未来动作步的监督强度。该方法不需要独立评分网络或部署时探针。基座从视频预训练骨干学习，无需中间阶段的外部具身数据预训练。我们评测固定基座及其智能体后训练、按任务选择的系统。在42项RoboDojo任务上，二者平均成功率分别为12.85%和15.62%，得分分别为17.86和20.59。在15项真机任务上，完整系统取得89.00%的任务宏平均成功率，比五个基线中的最优方法高37.67个百分点。在315个固定输出仿真窗口中，响应排名前20%的位置有45.21%位于误差排名前20%的集合之外，揭示了预测误差之外的信息。';
const methodCopy=[
{label:['FUTURE SUPERVISION','未来监督'],title:['Give action features a view of the future.','以未来视觉监督塑造动作表征。'],description:['Recorded future visual latents supervise 16 learned queries inside the joint predictor. Action tokens attend to these query features, connecting future visual supervision to the representations used for control. Coupled Action Projection (CAP) then reads out the action features.','记录的未来视觉潜变量监督联合预测器中的16个可学习查询。动作token读取这些查询特征，将未来视觉监督与控制所用的表征联系起来。耦合动作投影（Coupled Action Projection，CAP）进一步将动作特征映射为动作输出。'],takeaway:['Future-supervised queries shape the representation; CAP provides the action readout.','未来监督查询塑造表征，CAP提供动作读出接口。']},
{label:['PREDICTIVE REHEARSAL','预测演练'],title:['Turn predicted futures into training feedback.','让预测的未来进入学习闭环。'],description:['A predictor trained on recorded starting observations does not rehearse continuations from its own imperfect forecasts. Predictive rehearsal makes those forecasts part of the next training condition: generate one demonstration chunk, carry its last predicted observation into the following chunk, and learn from the recorded continuation.','仅以记录观测作为输入，模型不会演练如何从自身有偏差的预测继续推演。预测演练将这些预测转化为下一段的训练条件：先生成一个示范片段，以其末帧预测作为后续片段的初始观测，再以记录的后续观测和动作提供监督。'],takeaway:['One rehearsal, two roles: generated training conditions and a persistent-error prior.','一次演练，两种作用：构造预测输入条件，积累持续误差先验。']},
{label:['ACTION-RESPONSE CREDIT','动作响应信用分配'],title:['One response, two dimensions of supervision.','同一响应，引导两种维度的监督。'],description:['Perturb the noised action input while matching the observation, video noise, and diffusion level. The resulting video response, current error, and rehearsal prior guide spatial visual supervision. Spatially pooled responses guide supervision across future action steps.','在观测、视频噪声与扩散水平一致的条件下，扰动加噪动作输入。视频响应与当前误差、演练先验共同引导空间视觉监督；对响应进行空间汇总，进一步引导未来动作步的监督。'],takeaway:['No separate scoring network. No response probe at deployment.','无需独立评分网络，部署时无需响应探针。']}
];
function methodVisual(i){
 if(i===0)return `<div class="flow-nodes"><div class="flow-node"><div class="latent-grid" aria-hidden="true">${'<i></i>'.repeat(16)}<span>z</span></div><div class="flow-label">${t('Future latents','未来潜变量')}</div></div><span class="flow-arrow">→</span><div class="flow-node"><div class="query-grid" aria-hidden="true">${'<i></i>'.repeat(16)}</div><div class="flow-label">${t('16 predictive queries','16个预测查询')}</div></div><span class="flow-arrow">→</span><div class="flow-node"><div class="action-bars" aria-hidden="true">${[34,49,71,53,32,60,80,55].map(h=>`<i style="--h:${h}%"></i>`).join('')}</div><div class="flow-label">${t('Action features hₐ','动作特征 hₐ')}</div></div></div><div class="condition-flow">${t('Action tokens read future-supervised query features','动作token读取未来监督的查询特征')}</div>`;
 if(i===1)return `<div class="rehearsal-story"><div class="rehearsal-story-label">${t('SCHEMATIC TRAINING FLOW','训练流程示意')}</div><div class="rehearsal-chain"><div class="rehearsal-stage"><span class="stage-index">01</span><h4>${t('Predict chunk 1','预测片段1')}</h4><div class="forecast-strip" aria-hidden="true"><span>t+1</span><span>t+8</span><span class="selected-frame">t+16</span></div><p>${t('Generate future observations and actions','生成未来观测与动作')}</p></div><span class="rehearsal-arrow">→</span><div class="rehearsal-stage"><span class="stage-index">02</span><h4>${t('Rehearse chunk 2','演练片段2')}</h4><div class="prefix-and-targets" aria-hidden="true"><span class="generated-prefix">${t('Predicted prefix','预测前缀')}</span><span class="recorded-targets">${t('Recorded future','记录未来')}</span></div><p>${t('Carry the last prediction into the next condition','将末帧预测带入下一段条件')}</p></div></div><div class="rehearsal-feedback"><span>${t('Next-chunk prediction errors','下一段的预测误差')}</span><span>→</span><span class="prior-output">${t('Moving-average spatial prior ','移动平均空间先验 ')}<math class="math-symbol"><mi mathvariant="script">𝒫</mi></math></span></div></div>`;
 return `<div class="probe-rows"><div class="probe-block"><b><math class="math-symbol"><msub><mi>a</mi><mi>σ</mi></msub></math></b><br>${t('Noisy action input','加噪动作输入')}</div><span class="flow-arrow">→</span><div class="probe-block"><b><math class="math-symbol"><mi>v</mi></math></b><br>${t('Reference video velocity','参考视频速度预测')}</div><div class="probe-block"><b><math class="math-symbol"><msub><mi>a</mi><mi>σ</mi></msub><mo>+</mo><mi>δ</mi></math></b><br>${t('Perturbed noisy action','扰动后的加噪动作')}</div><span class="flow-arrow">→</span><div class="probe-block"><b><math class="math-symbol"><msup><mi>v</mi><mo>+</mo></msup></math></b><br>${t('Perturbed video velocity','扰动视频速度预测')}</div></div><div class="condition-flow">${t('Video response ','视频响应 ')}<math class="math-symbol"><mi mathvariant="script">𝒮</mi></math>${t(': channel-mean squared change in video velocity', '：对视频速度变化的平方取通道均值')}</div><div class="probe-out"><span>${t('Spatial visual supervision','空间视觉监督')}</span><span>${t('Temporal action supervision','时间动作监督')}</span></div>`;
}
function methodDetail(i){
 if(i===0)return `<div class="cap-explanation"><div><span class="eyebrow">${t('CAP EXPLAINED','理解CAP')}</span><h4>Coupled Action Projection <span>(CAP)</span></h4><p>${t('The video backbone needs an action-specific readout. CAP adds the contributions of a compact MLP and a sequence head conditioned on the diffusion noise level to produce one action-flow velocity. The branches are optimized together through their sum; denoising and unnormalization yield an executable robot action chunk.','视频骨干需要面向动作的读出接口。CAP将紧凑MLP与受扩散噪声水平调制的序列头相加，得到一个动作流速度输出。两个分支通过其和共同优化，经去噪和反归一化后生成可执行的机器人动作片段。')}</p></div><div class="cap-diagram" aria-label="Two projection branches sum into one action velocity"><div class="cap-input">h<sub>a</sub><small>${t('Action features','动作特征')}</small></div><span class="cap-arrow">→</span><div class="cap-heads"><span>H<sub>c</sub> · ${t('Compact MLP','紧凑MLP')}</span><span>H<sub>r</sub> · ${t('Noise-conditioned head','噪声调制序列头')}</span></div><span class="cap-plus">+</span><div class="cap-output"><math class="math-symbol"><msubsup><mi>v</mi><mi>θ</mi><mi>a</mi></msubsup></math><small>${t('One velocity output','一个速度输出')}</small></div></div><div class="cap-final">${t('Action velocity → denoise + unnormalize → robot action chunk','动作速度 → 去噪与反归一化 → 机器人动作片段')}</div></div>`;
 if(i===1)return `<div class="rehearsal-roles"><div><span class="role-number">01</span><h4>${t('Practice under generated conditions','在预测条件下演练')}</h4><p>${t('The starting observation comes from the preceding forecast, while the following recorded RGB frames and actions remain the supervision. This exposes the predictor to its own forecast deviations without replacing demonstrations with self-generated targets.','起始观测来自前一段的预测，后续记录的RGB帧与动作仍作为监督。模型因而能够接触自身预测的偏差，同时以示范数据作为学习锚点。')}</p></div><div><span class="role-number">02</span><h4>${t('Carry recurring difficulty into credit assignment','将持续困难带入信用分配')}</h4><p>${t('An exponential moving average accumulates the second chunk’s video-training errors into a spatial prior. Repeatedly difficult locations then inform response-based visual supervision alongside current error and action response.','对第二段预测误差进行指数移动平均，形成空间先验。反复难以预测的位置，将与当前误差、动作响应一起参与后续视觉监督的分配。')}</p></div></div>`;
 return '';
}
function setMethod(i){$$('[data-method]').forEach((b,j)=>{b.setAttribute('aria-selected',j===i);b.tabIndex=j===i?0:-1});$('#method-panel').setAttribute('aria-labelledby',`method-tab-${i}`);const c=methodCopy[i];$('#method-label').textContent=t(...c.label);$('#method-title').textContent=t(...c.title);$('#method-description').textContent=t(...c.description);$('#method-takeaway').textContent=t(...c.takeaway);$('#method-visual').innerHTML=methodVisual(i);$('#method-detail').innerHTML=methodDetail(i);$('#method-detail').hidden=i===2}
function tabKeyboard(list,selector,callback){list.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const bs=[...list.querySelectorAll(selector)];const i=bs.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?bs.length-1:(i+(e.key==='ArrowRight'?1:-1)+bs.length)%bs.length;callback(bs[n]);bs[n].focus()})}
$$('[data-method]').forEach(b=>b.addEventListener('click',()=>setMethod(+b.dataset.method)));tabKeyboard($('.method-tabs'),'button',b=>setMethod(+b.dataset.method));setMethod(0);
function renderRealOptions(){const select=$('#real-select');select.innerHTML=`<option value="macro">${t('15-task macro average','15任务宏平均')}</option>`+data.tasks.map(x=>`<option value="${x.id}">${String(x.id).padStart(2,'0')} · ${esc(lang==='en'?x.title:x.titleZh)}${x.supplementary?t(' (supplementary)','（补充）'):''}</option>`).join('');select.value=realTask}
function renderReal(){
 const task=realTask==='macro'?null:data.tasks.find(x=>x.id===+realTask),values=task?task.sr.map(v=>v===null?null:v*100):data.macro15;
 const colors=['#b8c0ba','#aebcaf','#9aac9a','#869f8b','#6c8879','#c95331'];
 $('#real-chart').innerHTML=data.methods.map((m,i)=>values[i]===null?'':`<div class="bar-row"><span class="bar-name">${esc(m)}</span><div class="bar-track"><div class="bar-fill" style="--value:${values[i]}%;--bar-color:${colors[i]}"></div></div><span class="bar-value">${values[i].toFixed(task?0:2)}</span></div>`).join('')+'<div class="axis" aria-hidden="true"><span>0</span><span>25</span><span>50</span><span>75</span><span>100%</span></div>';
 $('#real-value').innerHTML=`${values[5].toFixed(task?0:2)}<span>%</span>`;
 const best=Math.max(...values.slice(0,5).filter(v=>v!==null)),gap=values[5]-best;
 $('#real-insight').textContent=task?t(`${gap.toFixed(0)} percentage points above the strongest reported baseline for this task.`, `该任务比报告的最优基线高${gap.toFixed(0)}个百分点。`):t('37.67 percentage points above G0.5, the strongest baseline across the same 15 tasks.','在相同15任务范围内，比最优基线G0.5高37.67个百分点。');
 $('#real-footnote').textContent=task?.supplementary?t('Supplementary task. Only π0.5 and RAP-WAM results are reported; this task is excluded from the 15-task average.','补充任务。仅报告π0.5与RAP-WAM结果，不计入15任务宏平均。'):t('The macro average gives each of the 15 tasks equal contribution. Task order follows the experimental workbook; percentages are the reported success rates.','宏平均对15项任务等权计算。任务顺序与实验工作簿一致；百分比为报告的成功率。');
 $('#result-video-link').textContent=task?t('Watch this task ↗','观看该任务 ↗'):t('Explore the robot recordings ↗','浏览真机实录 ↗');
}
$('#real-select').addEventListener('change',e=>{realTask=e.target.value;renderReal()});$('#result-video-link').addEventListener('click',e=>{if(realTask!=='macro'){e.preventDefault();openVideo(+realTask)}});
function renderSim(){
 const sim=data.simulation,b=sim.baseAverage[metric],s=sim.systemAverage[metric],suffix=metric==='sr'?'%':'';
 $('#sim-base').textContent=b.toFixed(2)+suffix;$('#sim-system').textContent=s.toFixed(2)+suffix;$('#sim-gain').textContent='+'+(s-b).toFixed(2)+(metric==='sr'?t(' pp','个百分点'):t(' Score','分'));
 const max=metric==='sr'?45:60;
 $('#sim-chart').innerHTML=sim.capabilities.map(c=>`<div class="sim-group"><div class="sim-bars"><div class="sim-bar" style="--height:${sim.base[c][metric]/max*100}%"><span>${sim.base[c][metric].toFixed(2)}</span></div><div class="sim-bar" style="--height:${sim.system[c][metric]/max*100}%"><span>${sim.system[c][metric].toFixed(2)}</span></div></div><p>${esc(category(c))}</p></div>`).join('');renderSimTable();
}
function renderSimTable(){const q=$('#task-search').value.toLowerCase().trim(),rows=data.simulation.tasks.filter(x=>(x.title+' '+x.category+' '+category(x.category)).toLowerCase().includes(q));$('#sim-table-body').innerHTML=rows.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(category(x.category))}</td><td>${x.baseSr.toFixed(2)}%</td><td>${x.systemSr.toFixed(2)}%</td><td class="gain">${x.systemSr-x.baseSr>0?'+':''}${(x.systemSr-x.baseSr).toFixed(2)} ${t('pp','个百分点')}</td></tr>`).join('')||`<tr><td colspan="5">${t('No matching tasks.','没有匹配的任务。')}</td></tr>`}
$('#task-search').addEventListener('input',()=>data&&renderSimTable());$$('[data-metric]').forEach(b=>b.addEventListener('click',()=>{metric=b.dataset.metric;$$('[data-metric]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderSim()}));
function selectResult(which){$$('[data-result]').forEach(b=>{const active=b.dataset.result===which;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('#real-results').hidden=which!=='real';$('#sim-results').hidden=which!=='sim';if(data&&which==='sim')renderSim()}
$$('[data-result]').forEach(b=>b.addEventListener('click',()=>selectResult(b.dataset.result)));tabKeyboard($('.result-tabs'),'button',b=>selectResult(b.dataset.result));
function renderGallery(){const rows=data.tasks.filter(x=>filter==='All'||x.category===filter);$('#gallery-count').textContent=t(`${rows.length} recordings`,`${rows.length}项实录`);$('#gallery').innerHTML=rows.map(x=>`<button class="task-card" data-task="${x.id}" aria-label="${esc(t('Watch ','观看')+(lang==='en'?x.title:x.titleZh))}"><div class="task-thumb"><img src="${x.poster}" alt="${esc(lang==='en'?x.title:x.titleZh)}" width="800" height="450" loading="lazy"><span class="play-circle" aria-hidden="true">▷</span><span class="sr-badge">${Math.round(x.sr[5]*100)}% ${t('SR','成功率')}</span><span class="duration">${Math.floor(x.duration/60)}:${String(Math.floor(x.duration%60)).padStart(2,'0')}</span></div><div class="task-caption"><div class="task-meta"><span>${String(x.id).padStart(2,'0')} / ${esc(category(x.category))}</span>${x.supplementary?`<span>${t('SUPPLEMENTARY','补充任务')}</span>`:''}</div><h3>${esc(lang==='en'?x.title:x.titleZh)}</h3></div></button>`).join('');$$('[data-task]').forEach(b=>b.addEventListener('click',()=>openVideo(+b.dataset.task)))}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderGallery()}));
function openVideo(id){if(!data)return;const x=data.tasks.find(x=>x.id===id);modalTask=id;$('#hero-video').pause();$('#modal-title').textContent=lang==='en'?x.title:x.titleZh;$('#modal-category').textContent=`${String(id).padStart(2,'0')} / ${category(x.category)}`;$('#modal-description').textContent=t(`Reported task SR: ${Math.round(x.sr[5]*100)}% · Task execution recording · Original playback speed${x.supplementary?' · Supplementary task':''}`,`报告的任务成功率：${Math.round(x.sr[5]*100)}% · 任务执行实录 · 原速播放${x.supplementary?' · 补充任务':''}`);const v=$('#modal-video');v.src=x.video;v.poster=x.poster;v.muted=true;v.playbackRate=1;$$('[data-speed]').forEach(b=>{b.classList.toggle('active',b.dataset.speed==='1');b.setAttribute('aria-pressed',b.dataset.speed==='1')});if(!$('#video-dialog').open)$('#video-dialog').showModal();document.body.style.overflow='hidden';v.play().catch(()=>{})}
function closeVideo(){const v=$('#modal-video');v.pause();v.removeAttribute('src');v.load();$('#video-dialog').close();document.body.style.overflow='';resumeHero()}
$('#close-video').addEventListener('click',closeVideo);$('#video-dialog').addEventListener('cancel',e=>{e.preventDefault();closeVideo()});$('#video-dialog').addEventListener('click',e=>{if(e.target===$('#video-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeVideo()}});$('#prev-video').addEventListener('click',()=>openVideo((modalTask+14)%16+1));$('#next-video').addEventListener('click',()=>openVideo(modalTask%16+1));$$('[data-speed]').forEach(b=>b.addEventListener('click',()=>{$('#modal-video').playbackRate=+b.dataset.speed;$$('[data-speed]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)})}));
function predictionRows(){const q=$('#prediction-search').value.trim().toLowerCase();return data.predictions.filter(x=>x.domain===predDomain&&(!q||(x.title+' '+x.titleZh+' '+x.key).toLowerCase().includes(q)))}
function renderPredictionOptions(){
 const rows=predictionRows();if(rows.length&&!rows.some(x=>x.key===predKey))predKey=rows[0].key;
 $('#prediction-select').innerHTML=rows.map(x=>`<option value="${x.key}">${esc(lang==='en'?x.title:x.titleZh)}</option>`).join('');$('#prediction-select').value=predKey;$('#prediction-select').disabled=!rows.length;$('.prediction-layout').hidden=!rows.length;
 $('#prediction-count').textContent=t(`${rows.length} / ${data.predictions.filter(x=>x.domain===predDomain).length} examples`,`${rows.length} / ${data.predictions.filter(x=>x.domain===predDomain).length} 组样例`);$('#prediction-search').placeholder=t('Search tasks…','搜索任务…');renderPredictionStrip(rows);
}
function renderPredictionStrip(rows=predictionRows()){
 $('#prediction-strip').innerHTML=rows.map((x,i)=>`<button class="prediction-thumb ${x.key===predKey?'active':''}" data-pred-key="${x.key}" aria-pressed="${x.key===predKey}" aria-label="${esc(t('Compare ','对比')+(lang==='en'?x.title:x.titleZh))}"><img src="${x.assetPrefix}-recorded-16.webp" alt="" width="${x.width}" height="${x.height}" loading="lazy"><span>${esc(lang==='en'?x.title:x.titleZh)}</span></button>`).join('')||`<p>${t('No examples match your search.','没有匹配的样例。')}</p>`;
 $$('[data-pred-key]').forEach(b=>b.addEventListener('click',()=>{predKey=b.dataset.predKey;$('#prediction-select').value=predKey;renderPrediction()}));
}
function renderPrediction(){
 const p=data.predictions.find(x=>x.key===predKey);if(!p||!predictionRows().length)return;
 $('#predicted-frame').src=`${p.assetPrefix}-predicted-${offset}.webp`;$('#recorded-frame').src=`${p.assetPrefix}-recorded-${offset}.webp`;
 $('#comparison').style.aspectRatio=`${p.width} / ${p.height}`;
 const title=lang==='en'?p.title:p.titleZh;$('#recorded-frame').alt=t(`${p.domain==='real'?'Recorded':'Ground-truth'} future frame: ${title}, t + ${offset}`,`${p.domain==='real'?'录制':'真实'}未来帧：${title}，t + ${offset}`);$('#predicted-frame').alt=t(`Predicted future frame: ${title}, t + ${offset}`,`预测未来帧：${title}，t + ${offset}`);
 $('.label-recorded').textContent=p.domain==='real'?t('Recorded','录制帧'):t('Ground truth','真实帧');$('#prediction-time').textContent='t + '+offset;
 $('#prediction-ssim').textContent=p.metrics.ssim.toFixed(3);$('#prediction-lpips').textContent=p.metrics.lpips.toFixed(3);
 $('#prediction-sample-label').textContent=p.sampleType==='archived-training'?t('SAVED FINAL-STEP TRAINING EXAMPLE','训练末步保存的样例'):t('MATCHED TRAINING WINDOW','匹配的训练窗口');
 $('#prediction-paper-link').textContent=p.sampleType==='archived-training'?t('Read the method in the manuscript ↗','方法详见论文 ↗'):t('See the appendix for the full analysis ↗','完整分析见论文附录 ↗');
 $('#prediction-metric-note').textContent=p.metricBasis==='saved-rgb'?t('Metrics average the five paired RGB frames in the saved training visualization. This additional example is separate from the execution success-rate evaluation.','指标取保存的训练可视化中五组成对RGB帧的均值。该新增样例与执行成功率评测分别报告。'):t('Metrics average the five displayed future offsets. These are training-sample diagnostics, separate from the physical success-rate evaluation.','指标取五个展示未来时刻的均值。这些是训练样本诊断，与真机成功率评测分别报告。');

 $$('[data-offset]').forEach(b=>{b.classList.toggle('active',+b.dataset.offset===offset);b.setAttribute('aria-pressed',+b.dataset.offset===offset)});
 $$('[data-pred-key]').forEach(b=>{const active=b.dataset.predKey===predKey;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});
 const thumb=$(`[data-pred-key="${predKey}"]`);if(thumb){const strip=$('#prediction-strip');const center=thumb.getBoundingClientRect().left-strip.getBoundingClientRect().left+strip.scrollLeft+thumb.offsetWidth/2;strip.scrollTo({left:center-strip.clientWidth/2,behavior:'instant'})}
}
$('#prediction-select').addEventListener('change',e=>{predKey=e.target.value;renderPrediction()});
$('#prediction-search').addEventListener('input',()=>{renderPredictionOptions();renderPrediction()});
$$('[data-pred-domain]').forEach(b=>b.addEventListener('click',()=>{predDomain=b.dataset.predDomain;$('#prediction-search').value='';$$('[data-pred-domain]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderPredictionOptions();renderPrediction()}));
function stepPrediction(direction){const rows=predictionRows();if(!rows.length)return;const i=rows.findIndex(x=>x.key===predKey);predKey=rows[(i+direction+rows.length)%rows.length].key;$('#prediction-select').value=predKey;renderPrediction()}
$('#prediction-prev').addEventListener('click',()=>stepPrediction(-1));$('#prediction-next').addEventListener('click',()=>stepPrediction(1));
$$('[data-offset]').forEach(b=>b.addEventListener('click',()=>{offset=+b.dataset.offset;renderPrediction()}));
$('#compare-range').addEventListener('input',e=>{const n=e.target.value;$('#recorded-layer').style.clipPath=`inset(0 ${100-n}% 0 0)`;$('#divider').style.left=n+'%'});
let heroVisible=false,heroPausedByUser=reduced;
function resumeHero(){if(heroVisible&&!heroPausedByUser&&!document.hidden&&!$('#video-dialog').open)$('#hero-video').play().catch(()=>{})}
const hero=$('#hero-video');new IntersectionObserver(entries=>{heroVisible=entries[0].isIntersecting;if(heroVisible)resumeHero();else hero.pause()},{threshold:.15}).observe(hero);
$('#hero-toggle').addEventListener('click',()=>{heroPausedByUser=!hero.paused;if(hero.paused){heroPausedByUser=false;hero.play().catch(()=>{})}else hero.pause()});hero.addEventListener('play',()=>{$('#hero-toggle').textContent='Ⅱ';$('#hero-toggle').setAttribute('aria-label',t('Pause highlights','暂停精华视频'))});hero.addEventListener('pause',()=>{$('#hero-toggle').textContent='▷';$('#hero-toggle').setAttribute('aria-label',t('Play highlights','播放精华视频'))});$('#hero-full').addEventListener('click',()=>{const el=$('.cinema');if(el.requestFullscreen)el.requestFullscreen();else if(hero.webkitEnterFullscreen)hero.webkitEnterFullscreen()});
function updateHeroTask(){if(!data?.highlightSegments?.length)return;const segment=data.highlightLoopTransition&&hero.currentTime>=data.highlightLoopTransition.labelSwitch?data.highlightSegments[0]:(data.highlightSegments.find(s=>hero.currentTime>=s.start&&hero.currentTime<s.end)||data.highlightSegments[data.highlightSegments.length-1]);const task=data.tasks.find(x=>x.id===segment.id);$('#hero-task').textContent=lang==='en'?task.title:task.titleZh}
hero.addEventListener('timeupdate',updateHeroTask);document.addEventListener('visibilitychange',()=>{if(document.hidden)hero.pause();else resumeHero()});
$('#open-overview').addEventListener('click',()=>{$('#image-dialog').showModal();document.body.style.overflow='hidden';hero.pause()});function closeImage(){$('#image-dialog').close();document.body.style.overflow='';resumeHero()}$('#close-image').addEventListener('click',closeImage);$('#image-dialog').addEventListener('cancel',e=>{e.preventDefault();closeImage()});
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$('#copy-citation').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#bibtex').textContent);toast(t('BibTeX copied','已复制BibTeX'));$('#copy-status').textContent=t('Citation copied to clipboard.','引用已复制。')}catch{const range=document.createRange();range.selectNodeContents($('#bibtex'));window.getSelection().removeAllRanges();window.getSelection().addRange(range);toast(t('Citation selected. Use your copy shortcut.','已选中引用，请按复制快捷键。'))}});
$('#download-results').addEventListener('click',()=>{const rows=[['Task ID','Task',...data.methods],...data.tasks.map(x=>[x.id,x.title,...x.sr.map(v=>v===null?'':(v*100).toFixed(2))]),['01–15','15-task macro average',...data.macro15.map(v=>v.toFixed(2))]];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='rap-wam-real-robot-results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
function setLanguage(value){lang=value;document.documentElement.lang=lang==='en'?'en':'zh-CN';$$('[data-en][data-zh]').forEach(el=>{if(lang==='en')el.innerHTML=englishMarkup.get(el);else el.textContent=el.dataset.zh});$('#language').textContent=lang==='en'?'中文':'EN';$('#language').setAttribute('aria-label',t('Switch to Chinese','切换至英文'));$('#abstract-text').textContent=lang==='en'?abstractEn:abstractZh;const active=+$('[data-method][aria-selected=true]').dataset.method;setMethod(active);if(data){renderRealOptions();renderReal();renderSim();renderGallery();renderPredictionOptions();renderPrediction();updateHeroTask()}try{localStorage.setItem('rap-wam-language',lang)}catch{}}
$('#language').addEventListener('click',()=>setLanguage(lang==='en'?'zh':'en'));$('#abstract-text').textContent=abstractEn;
fetch('data/results.json?v=20261010-22').then(r=>{if(!r.ok)throw new Error('Results unavailable');return r.json()}).then(d=>{data=d;let initial='en';try{initial=localStorage.getItem('rap-wam-language')==='zh'?'zh':'en'}catch{}setLanguage(initial)}).catch(e=>{console.error(e);$('#gallery').innerHTML='<p>The videos and results could not load. Please refresh, or download the manuscript above.</p>'});
$('#menu-toggle').addEventListener('click',()=>{const open=$('#mobile-nav').hidden;$('#mobile-nav').hidden=!open;$('#menu-toggle').setAttribute('aria-expanded',open)});$$('#mobile-nav a').forEach(a=>a.addEventListener('click',()=>{$('#mobile-nav').hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false')}));
const navLinks=$$('nav a');new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('current',a.hash==='#'+e.target.id))}})},{rootMargin:'-10% 0px -65% 0px'}).observe($('#method'));for(const id of ['results','demos','predictions'])new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>a.classList.toggle('current',a.hash==='#'+e.target.id))})},{rootMargin:'-10% 0px -65% 0px'}).observe($('#'+id));
